"""baseline — full tenancy / provenance / audit / resume / PII schema + product tables + RLS

Single replayable baseline. It creates **every table currently on the ORM metadata**
(Phase 0 spine + the Phase 1 product tables) and then layers the DDL the ORM can't
express: the citext/vector extensions, the embedding HNSW index, the role-taxonomy
seed, the non-superuser/non-BYPASSRLS ``manfriday_app`` role + least-privilege grants
(``audit_event`` and ``consent_ledger`` are INSERT-only), and ENABLE + FORCE Row-Level
Security with a ``tenant_isolation`` policy on every tenant-scoped table (invariant #3).

Because the baseline materializes the schema via ``Base.metadata.create_all`` (live
metadata), it intentionally reflects the current models as ONE artifact rather than a
chain of ALTERs — adding a model = it appears here on the next replay. (Switching to
frozen, autogenerated incremental migrations is a deliberate future step, needed once
there is production data to preserve.) Replayable from scratch.

Phase 1 additions folded in here: new ``candidate`` columns (per-org consent_*, status)
and ``requisition`` / ``jd_skill`` / ``proposal`` / ``consent_ledger``. Candidates stay
strictly org-isolated (invariant #3) — there is deliberately no cross-org link; a person
in two orgs is incidental duplication, never a shared record.

Revision ID: 0001
Revises:
Create Date: 2026-05-29

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from app.db import models  # noqa: F401  (registers all tables on Base.metadata)
from app.db.base import Base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (table, RLS-key column) for every tenant-scoped table. `role` is a global lookup.
TENANT_TABLES: list[tuple[str, str]] = [
    ("organization", "id"),
    ("client", "org_id"),
    ("app_user", "org_id"),
    ("membership", "org_id"),
    ("candidate", "org_id"),
    ("embedding", "org_id"),
    ("parse_run", "org_id"),
    ("scoring_run", "org_id"),
    ("generation_run", "org_id"),
    ("score", "org_id"),
    ("resume", "org_id"),
    ("audit_event", "org_id"),
    ("tenant_key", "org_id"),
    # Phase 1 product tables.
    ("requisition", "org_id"),
    ("jd_skill", "org_id"),
    ("proposal", "org_id"),
    ("consent_ledger", "org_id"),
]
_PRED = "{col} = NULLIF(current_setting('app.current_org', true), '')::uuid"


def upgrade() -> None:
    bind = op.get_bind()

    # Extensions must exist before tables that use citext / vector columns.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # All tables + their btree/unique indexes, from the ORM metadata.
    Base.metadata.create_all(bind)

    # HNSW index for cosine ANN (needs an opclass — not expressible in ORM metadata).
    op.execute(
        "CREATE INDEX ix_embedding_vector_hnsw ON embedding "
        "USING hnsw (vector vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )

    # Global role taxonomy.
    op.execute(
        "INSERT INTO role (key) VALUES "
        "('recruiter'),('agency_admin'),('client_hiring_manager'),"
        "('candidate'),('auditor'),('platform_super_admin') ON CONFLICT (key) DO NOTHING"
    )

    # Application role: LOGIN, NOT superuser, NOT BYPASSRLS, so RLS applies. Local dev
    # uses trust auth; real envs set auth out-of-band via secrets + pg_hba.
    op.execute(
        """
        DO $$ BEGIN
          IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'manfriday_app') THEN
            CREATE ROLE manfriday_app LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
          END IF;
        END $$;
        """
    )

    # Least-privilege grants. DDL stays with the owner; the app only does DML.
    op.execute("GRANT USAGE ON SCHEMA public TO manfriday_app")
    op.execute("GRANT SELECT ON role TO manfriday_app")
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON "
        "organization, client, app_user, membership, candidate, embedding, "
        "parse_run, scoring_run, generation_run, score, "
        "requisition, jd_skill, proposal TO manfriday_app"
    )
    op.execute("GRANT SELECT, INSERT, UPDATE ON resume TO manfriday_app")
    op.execute("GRANT SELECT, INSERT, DELETE ON tenant_key TO manfriday_app")
    # audit_event and consent_ledger are append-only: SELECT + INSERT; UPDATE/DELETE revoked.
    op.execute("GRANT SELECT, INSERT ON audit_event TO manfriday_app")
    op.execute("REVOKE UPDATE, DELETE ON audit_event FROM manfriday_app")
    op.execute("GRANT SELECT, INSERT ON consent_ledger TO manfriday_app")
    op.execute("REVOKE UPDATE, DELETE ON consent_ledger FROM manfriday_app")

    # Row-Level Security on every tenant-scoped table. FORCE so it applies even to
    # the table owner; the policy covers reads (USING) and writes (WITH CHECK).
    for table, col in TENANT_TABLES:
        predicate = _PRED.format(col=col)
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'manfriday_app') THEN
            EXECUTE 'DROP OWNED BY manfriday_app';
            DROP ROLE manfriday_app;
          END IF;
        END $$;
        """
    )
